#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Xakki\Emailer;
use Monolog\Level;
use Monolog\Logger;
use Monolog\Handler\FirePHPHandler;
use Monolog\Handler\StreamHandler;
use Monolog\Formatter\JsonFormatter;

$config = new Emailer\ConfigService(include __DIR__ . '/config/' . getenv('ENV') . '.php');

$logger = new Logger('console');
$handler = new StreamHandler(
    '/var/log/app.log',
    getenv('DEBUG_MODE') ? Level::Debug : Level::Warning
);
$handler->setFormatter(new JsonFormatter());
$logger->pushHandler($handler);
$logger->pushHandler(new FirePHPHandler());

$emailer = new Emailer\Emailer($config, $logger);
echo PHP_EOL . $emailer->dispatchConsole(array_slice($_SERVER['argv'], 1)) . PHP_EOL;
